### ISSUE TITLE
New logo for ReZoom

### ISSUE THREAD

**Issue by reallinfo** [rspeele/Rezoom#2]
I wanted to contribute to ReZoom. I designed a logo for ReZoom. If you like it, I'll send you the files.

![reezoom](https://user-images.githubusercontent.com/36298335/37734935-475482a2-2d55-11e8-8adc-3a7fbd17feec.jpg)

**Comment by rspeele** [comment]
Hi,

It's a good looking logo, but I don't think it matches what the project does.

Admittedly that is partially my fault for giving the project this dumb name. But it has nothing to do with zooming in (like with a magnifying glass). Rather, it's called Rezoom because it's based on the concept of a resumption monad (resume) and is intended to make your data access code go fast (zoom).

I'm worried that, with the name already being confusing enough, the logo will make visitors think that the project has to do with zooming images or something like that.

Thank you for your efforts.

Regards,
Robert

**Comment by reallinfo** [comment]
Oh, sorry. I Thank you. Goodluck!
